# -*- coding: utf-8 -*-
"""augustinhp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fIFSMpC-umuGjHjSsZdVDVeTiVdTNlym
"""

registros = []

def mostra_memoria():
    global registros
    print(registros)

def memoria():
    global registros

    for i in range(10):
        registros.append(0)

    return registros

cmd = ""

memoria()

while cmd != 'HALT':
    cmd = input('Digite o comando:')
    elementos = cmd.split(' ')

    if len(elementos) == 2:
        param = elementos[1].split(',')
        p1 = param[0]
        p2 = param[1]

        if elementos[0] == 'LOAD':
            if p2.startswith('R'):
                posicao_origem = int(p2[1:])
                posicao_destino = int(p1[1:])
                registros[posicao_destino] = registros[posicao_origem]
                mostra_memoria()
            else:
                posicao = int(p1[1:])
                registros[posicao] = int(p2)
                mostra_memoria()
        elif elementos[0] == 'ADD':
            if p2.startswith('R'):
                posicaoOrigem = int(p2[1:])
                posicaoDestino = int(p1[1:])
                registros[posicaoDestino] += registros[posicaoOrigem]
                mostra_memoria()
            else:
                posicao = int(p1[1:])
                registros[posicao] += int(p2)
                mostra_memoria()

    print('comando:', elementos[0], 'param:', elementos[1])